### ISSUE TITLE
Unable to compile: /usr/bin/ld: cannot find -lsqlite3

### ISSUE THREAD

**Issue by mllnd** [L2-Technology/sensei#14]
Hi, wanted to take Sensei for a test run, but it does not compile out of the box on Ubuntu 20.04 LTS. Followed the exact steps as pointed out in the documentation.

It seems that `sqlite3` is a native dependency. Managed to fix this by installing `libsqlite3-dev` package, but perhaps there is a more elegant way?

Some logs for context (redacted a bit):

```
...
   Compiling hyper-system-resolver v0.5.0
   Compiling hyper-timeout v0.4.1
   Compiling axum v0.4.2
   Compiling sensei v0.0.1 (/home/ln/sensei)
   Compiling lightning-background-processor v0.0.104
   Compiling bdk-ldk v0.1.0 (https://github.com/johncantrell97/bdk-ldk#aff5a99953121ad3eaed7a415c2f6d208d2df46f#44a05572)
   Compiling public-ip v0.2.1
   Compiling tonic v0.6.1
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/ln/sensei/target/debug/deps/senseid-508ae6de589bc161.104sprq0wmc0nwqz.rcgu.o" "/home/ln/sensei/target/debug/deps/senseid-508ae6de589bc161.10dqks9bz09pn0q6.rcgu.o" "/home/ln/sensei/target/debug/deps/senseid-508ae6de589bc161.10ifzglyqw0ziooh.rcgu.o" "/home/ln/sensei/target/debug/deps/senseid-508ae6de589bc161.10jeq6taq34xmthb.rcgu.o" "/home/ln/sensei/target/debug/deps/senseid-508ae6de589bc161.10l5cfn5ni3fz2xb.rcgu.o" 
  ...
```
Final error message:

```
  = note: /usr/bin/ld: cannot find -lsqlite3
          collect2: error: ld returned 1 exit status


error: could not compile `sensei` due to previous error
```

**Comment by johncantrell97** [comment]
Ah thanks for pointing that out.  Yeah, we should probably just add the `bundled` feature for the `rusqlite` crate that is used for sqlite support.  Adding this feature will remove the requirement for having libsqlite3 on your system (I think).

**Comment by johncantrell97** [comment]
just pushed this to `main`. can you try again and see if it's resolved? thank you!

**Comment by mllnd** [comment]
Compiles perfectly now. Thanks!

**Comment by johncantrell97** [comment]
Awesome!
