### ISSUE TITLE
Persist all node state in database

### ISSUE THREAD

**Issue by johncantrell97** [L2-Technology/sensei#23]
Currently the database stores some but not all of the data relevant to a node.  I think we probably want to store everything in the database to remove reliance on the filesystem.  This is a little bit of a scary task because persisting the channel state (monitors, managers) needs to be handled with care so users don't lose funds.  

Probably just want to use same format/structure the out-of-the-box FilesystemPersister uses as most databases support BLOB storage.

**Comment by orbitalturtle** [comment]
Looking into this :)

**Comment by orbitalturtle** [comment]
@johncantrell97 Oh cool, sounds good, I'll shoot you a message when I'm back from my travels and show you what I have so far / see if we can merge our work, or if you're already far along I can work on something else :)

**Comment by johncantrell97** [comment]
sounds good -- I was headed down a path of basically supporting a generic persistence layer for all of the files that are currently stored on filesystem (manager, monitors, scorer, network_graph, etc).  Idea being filesystem would be just one-of-many possible stores for them.  They're slightly different then the other db tables since you are never really querying them.  It's more of a generic key-value store that is needed.
