### ISSUE TITLE
display version number

### ISSUE THREAD

**Issue by johncantrell97** [L2-Technology/sensei#43]
We should surface the version number in the ui somewhere.  How about in the bottom left of the nav below logout?

I'm not actually sure of the best way to grab the version from cargo.toml.  I think there's some way to grab it as part of the build metadata or something.  Anyone know how to make it available at runtime?

**Comment by louneskmt** [comment]
I've been looking into this, and looks like there is two way of doing that:
1) get the version directly from Cargo environment ([source](https://stackoverflow.com/a/34612332))
```rust
const VERSION: &'static str = env!("CARGO_PKG_VERSION");
```
2) do [something like lnd](https://github.com/lightningnetwork/lnd/blob/440f4d982c67aec6105657cf62abbc966ae72d3c/build/version.go#L69), and hardcode the version on each update ([example](https://github.com/lightningnetwork/lnd/commit/62e4ce271a97df183f84c08b17a21d976a51be83))
```rust
// src/version.rs
use std::fmt;

const appMajor: u8 = 0,
const appMinor: u8 = 2,
const appPatch: u8 = 1,
const appPreRelease: String = "",

pub fn version() -> Result<String> {
    let version = fmt:format!("{}.{}.{}", appMajor, appMinor, appPatch);

    if !appPreRelease.is_empty() {
        version = fmt:format!("{}-{}", version, appPreRelease);
    }

    Ok(version)
}

```

The second one seems more reliable and clean. Thoughts?

**Comment by johncantrell97** [comment]
Thanks for lookin at some options.  I guess being explicit in the second one is nice. It does have the downside of the possibility of version numbers being out-of-sync.  However, i'd guess the cargo.toml version is not really used for binaries much since it's not going to be on crates.io or similar.

I don't really feel strongly about it, let's go with the 2nd one?

**Comment by louneskmt** [comment]
I agree that using the version could lead to unpredictable issues. 

Bumping the version should be included in the pre-release checklist (e.g. alongside tests), and be the final commit before release. Could be interesting to have a this checklist, if it doesn't exist yet. 

If we go for the second way, what do you think of the code fragment I sent?

**Comment by johncantrell97** [comment]
looks good to me! can be a separate task but we'll need a way to get the version.  maybe a /info endpoint or just add it to the status endpoint

**Comment by louneskmt** [comment]
I planned to add a `version` key to the `NodeInfo` object returned by `/v1/node/info`. 

If that seems okay, will open a PR tonight to add the version code + modified HTTP/gRPC.

**Comment by johncantrell97** [comment]
surfaced the version number in the ui in #91
