### ISSUE TITLE
investigate using `sqlx`, `SeaORM`, `diesel`, or maybe `prisma-client-rust` project

### ISSUE THREAD

**Issue by johncantrell97** [L2-Technology/sensei#54]
I've been a long-time user of Prisma in my typescript web projects and absolutely love it.  

Aside from the improved developer experience I think it would also help alleviate some pain around maintaining/building support for multiple database backends.  With Prisma you define your schema once in their dsl and then can generate clients that work with sqlite, postgres, mysql, and even mongodb.  

Main downside is that this is a brand new project by an individual and not actively maintained by Prisma. 

Not sure if anyone else has other thoughts on this but I'm tempted to try it out.

**Comment by johncantrell97** [comment]
I guess as part of this should also just look at more properly maintained alternatives like SeaORM https://sea-ql.org/SeaORM/

oo or if we want to avoid a full blown ORM we can go one level lower https://github.com/launchbadge/sqlx for native / implementation agnostic sql

**Comment by johncantrell97** [comment]
sqlx looks really nice to me.  looking at the support for `Any` database drive to handle deciding on the db (postgres/sqlite/mysql) at runtime.

**Comment by praveenperera** [comment]
I've used `sqlx` before I really liked it

**Comment by johncantrell97** [comment]
closing in favor of #55
