### ISSUE TITLE
Upon "child node" creation, return enough information to connect to the node

### ISSUE THREAD

**Issue by litch** [L2-Technology/sensei#70]
Currently, when you create a child node, the response object is:

https://github.com/L2-Technology/sensei/blob/main/proto/sensei.proto#L115

`pubkey` and `macaroon`.  Both of which are awesome things to have.

However, to actually connect to the node, we need the rest of the connection string.  Currently this is only available in the `ListNode` object (https://github.com/L2-Technology/sensei/blob/main/proto/sensei.proto#L40), which is retrievable by paging through the `ListNodes` request/responses.

It would be wonderful if we could surface the full node info both in the `CreateNodeResponse` and the `Info`/`GetInfo` for a given node.

https://github.com/L2-Technology/sensei/blob/main/proto/sensei.proto#L331

**Comment by johncantrell97** [comment]
yeah, agreed -- seems like at a minimum listen_port should be returned.  in theory you should know or have set the listen_addr but can't hurt to add that in there just in case.

I guess as you suggest, maybe just returning the ListNode response for create/start endpoints is simplest way forward.  That way it's consistent regardless of the request.

**Comment by orbitalturtle** [comment]
I'm looking into this, just fyi

**Comment by johncantrell97** [comment]
ha, was literally sitting down to add this now but I'll hold off if you think you'll have a pr ready in a bit?

**Comment by orbitalturtle** [comment]
@johncantrell97 Ha, ooops funny timing. Yup I should be able to get this in pretty quick
