### ISSUE TITLE
Consider adding Sensei to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [L2-Technology/sensei#71]
Hey @johncantrell97, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by johncantrell97** [comment]
cool! will add it for sure

**Comment by johncantrell97** [comment]
oh, looks like someone already did it! closing this

**Comment by billy1624** [comment]
Thanks! @johncantrell97
