### ISSUE TITLE
phantom payments / multi-node receive support

### ISSUE THREAD

**Issue by johncantrell97** [L2-Technology/sensei#8]
this is a new feature landing in ldk 105 that allows the creation of 'phantom' invoices.  the idea is you can run a small cluster of nodes and then generate an invoice that any one of them can pay.  this functionality is enabled by actually paying to a 'phantom' node that does not exist but any of the nodes in the cluster can fulfill the payment.

this provides reliability in case a node goes down or has no liquidity -- the payment can be retried and other nodes in the cluster can step up to handle it. 

think this can be as easy as supporting manual entry of other sensei nodes in your cluster and then a new flow for generating a phantom invoice against this cluster.

**Comment by dunxen** [comment]
I can take a look at this.

**Comment by dunxen** [comment]
The [invoice expiry for the phantom invoice utility functions](https://github.com/lightningdevkit/rust-lightning/commit/8f047ca23f73625e3889d2a2ce7deca4ae194eaf) will be in LDK 107 if we need that too.

**Comment by johncantrell97** [comment]
implemented in #139
